baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Margaux Vellucci'
theme = 'ananke'

# Markdown configuration
[markup]
  [markup.goldmark]
    # Enable extensions for Goldmark
    [markup.goldmark.extensions]
      table = true
      strikethrough = true
      tasklist = true
    smartypants = true

